%.html: %-b.html
	/anfs/www/tools/bin/ucampas $*-b.html
	chmod a+r $*.html

all: contributions.html index.html features.html get_started.html licensing.html

clean:
	rm -rf contributions.html index.html features.html get_started.html licensing.html
